[workspace]
name = "chipseq-notebook"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-arm64", "osx-64"]

[dependencies]
python = ">=3.11,<3.13"
jupyterlab = "*"
notebook = "*"
pandas = "*"
matplotlib = "*"
quarto = ">=1.9.38,<2"
biopython = ">=1.87,<2"


[feature.bioinformatics.dependencies]
bowtie2 = "*"
samtools = "*"
bedtools = "*"
macs3 = "*"
r-base = "4.3.*"
r-ggplot2 = "*"

[environments]
default = ["default"]
bioinf = { features = ["bioinformatics"] }

[tasks]
lab = "jupyter lab"
notebook = "jupyter notebook"
check-tools = "which bowtie2 && which samtools && which bedtools && which macs3 && R --version"

[tasks.preview]
args = [{"arg" = "profile", default = "exercise" }]
cmd = "quarto preview chip_seq_2026.qmd --to html --profile {{ profile }}"
cwd = "quarto"

[pypi-dependencies]
course-utils = { path = "course-utils", editable = true }
