project:
  title: "chip_seq_2026"
  output-dir: "_render/"
  render:
    - chip_seq_2026.qmd

filters:
- strip-solution
- filters/embed-ipynb-images.lua

format:
  ipynb:
    wrap: none    
    toc: true
    output: true    
  typst:
    number-sections: true
    number-depth: 2
    toc: true
    toc-depth: 2
    margin:
      left: 2cm
      right: 2cm
      top: 2.5cm
      bottom: 2.5cm

